M48
; DRILL file {KiCad 6.0.9+dfsg-1~bpo11+1} date vie 30 dic 2022 18:56:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-30T18:56:50-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9+dfsg-1~bpo11+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
%
G90
G05
T1
X5.4724Y-2.9921
T2
X5.2362Y-2.311
X5.3346Y-2.311
X5.4331Y-2.311
T0
M30
