M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date dom 29 ene 2023 22:13:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-29T22:13:54-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X6.5148Y-3.9764
X6.5148Y-4.2815
X6.623Y-3.9764
X6.623Y-4.2815
T2
X5.498Y-3.1726
X5.998Y-3.1726
T0
M30
